### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by sakonachhoeurng** [paulgibbs/behat-wordpress-extension#105]
I think it already has an issue similarly with https://github.com/paulgibbs/behat-wordpress-extension/issues/47
But I do has another different scenario as show below.
`behat.yml`
```
PaulGibbs\WordpressBehatExtension:
      path: /home/sakona/dev/docker-projects/wordpress/local.tornio.wehost.asia/wp
      users:
        admin:
          username: essentials
          password: webessentials
```
I do not know what is different with `path /wp` because my website create another them outside `/wp` folder
My error on scenario 
```
Scenario: Login to backend         # features/homepage.feature:12
    Given I am on "wp/wp-admin"      # Behat\MinkExtension\Context\MinkContext::visit()
    Given I am logged in as an admin # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmLoggedInAs()
      Fatal error: Call to a member function focus() on null (Behat\Testwork\Call\Exception\FatalThrowableError)

--- Failed scenarios:
```
Please help for this issue, I do not know how to solve.

**Comment by paulgibbs** [comment]
This was resolved in Slack: see https://wordhat.slack.com/archives/C472TKN79/p1498467642676483 onwards

**Comment by ataylorme** [comment]
@paulgibbs I'm having the same issue with admin login returning

```
Given I am logged in as an admin             # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmLoggedInAs()
      Fatal error: Call to a member function focus() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
```

I'd love to see the comments in Slack but the group seems to be private as it's asking me to login or contact the admin for an invite.

I also have WordPress core in it's own subdirectory (`/wp`), which is set in `path`. Not sure if that is having an effect.

**Comment by paulgibbs** [comment]
@ataylorme I don't know if it's possible to have the Slack logs public. I can't see a quick setting to change that. However, our Slack is easy to join, if you want to do that: https://wordhat.herokuapp.com

If you look at a sample config here https://gist.github.com/paulgibbs/6614745bb3fbf7e07de98d852c0fa751 and compare it to yours, you might need to set `site_url` if this is the same problem as the original poster had. Otherwise, we'll take a look.

@stephenharris if this is another "WP not in the specified path" thing, we gotta throw a meaningful exception somewhere.

**Comment by ataylorme** [comment]
Thanks @paulgibbs - adding `site_url` did it for my custom scenarios. For the bundled `login.feature` though I still get the following:

```
Feature: Logging in, Logging out

  @javascript
  Scenario: I can log-in and out     # features/login.feature:4
    Given I am logged in as an admin # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmLoggedInAs()
      Fatal error: Call to a member function focus() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
    And I am on the Dashboard        # PaulGibbs\WordpressBehatExtension\Context\DashboardContext::iAmOnDashboard()
    Then I should see "Howdy"        # Behat\MinkExtension\Context\MinkContext::assertPageContainsText()
    When I log out                   # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmAnonymousUser()
    Then I should not see "Howdy"    # Behat\MinkExtension\Context\MinkContext::assertPageNotContainsText()

  Scenario: I can log-in and out (no-js) # features/login.feature:11
    Given I am logged in as an admin     # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmLoggedInAs()
    And I am on the Dashboard            # PaulGibbs\WordpressBehatExtension\Context\DashboardContext::iAmOnDashboard()
    Then I should see "Howdy"            # Behat\MinkExtension\Context\MinkContext::assertPageContainsText()
    When I log out                       # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmAnonymousUser()
    Then I should not see "Howdy"        # Behat\MinkExtension\Context\MinkContext::assertPageNotContainsText()

--- Failed scenarios:

    features/login.feature:4

2 scenarios (1 passed, 1 failed)
10 steps (5 passed, 1 failed, 4 skipped)
0m34.28s (16.49Mb)
```
